AWSTemplateFormatVersion: '2010-09-09'
Description: Auth0 Custom CloudFormation Provider
Parameters:
  DefaultSecurityGroup:
    Type: String
    Default: ''
  S3BucketPrefix:
    Type: String
    Default: ''
  CFNCustomProviderZipFileName:
    Type: String
    Default: lambdas/cfn-saml-provider-1.0.0.zip
Resources:
  CFNCustomProvider:
    Type: AWS::Lambda::Function
    DependsOn:
      - LambdaRole
    Properties:
      Description: Custom SAML Provider CloudFormation Provider
      PackageType: Image
      Code:
        ImageUri: 463637877380.dkr.ecr.eu-central-1.amazonaws.com/xebia/cfn-saml-provider:1.0.0-db52506-dirty
      FunctionName: cfn-saml-provider
      MemorySize: 128
      Timeout: 10
      Role: !GetAtt 'LambdaRole.Arn'
  LambdaPolicy:
    Type: AWS::IAM::Policy
    DependsOn:
      - LambdaRole
    Properties:
      PolicyName: CFNCustomProviderPolicy
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - iam:CreateSAMLProvider
              - iam:UpdateSAMLProvider
              - iam:DeleteSAMLProvider
            Resource: '*'
      Roles:
        - !Ref 'LambdaRole'

  LambdaRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
