---
AWSTemplateFormatVersion: '2010-09-09'
Description: Demo SAML Custom Provider

Resources:
  SAMLProvider:
    Type: Custom::SAMLProvider
    Properties:
      ServiceToken: !Sub 'arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:cfn-saml-provider'
      Name: !Sub 'saml-provider-${AWS::StackName}'
      URL: 'https://mvanholsteijn.eu.auth0.com/samlp/metadata/ZALyvKmxYYlTmfHW4m4lzkia60S1YsSf'


Outputs:
  SAMLProvider:
    Description: Arn of the SAML provider
    Value: !Ref 'SAMLProvider'
